site_name: JustinWritesCode Documentation
site_description: JustinWritesCode Documentation
site_url: https://justinwritescode.com
site_author: "Justin Chase"
repo_url: https://github.com/justinwritescode/Types
repo_name: justinwritescode/Types
edit_uri: "tree/main/docs"
docs_dir: docs
nav:
  - Types: index.md
