//
// <auto-generated>
//     This code was generated by a tool.
//     Do not modify this file directly.
// </auto-generated>
//
// FILENAME
//
//   Generated: TIMESTAMP
//
//
//   Copyright © YEAR
//      License: LICENSE (https://opensource.org/licenses/LICENSE)
//
