// 
// CodeHeader.cs
// 
//   Created: 2022-10-30-05:42:40
//   Modified: 2022-11-11-04:49:45
// 
//   Author: Justin Chase <justin@justinwritescode.com>
//   
//   Copyright © 2022 Justin Chase, All Rights Reserved
//      License: MIT (https://opensource.org/licenses/MIT)
// 

// BEGIN
//
// <auto-generated>
//     This code was generated by a tool.
//     Do not modify this file directly.
// </auto-generated>
// 
// FILENAME
// 
//   Generated: TIMESTAMP
// 
//
//   Copyright © YEAR
//      License: LICENSE (https://opensource.org/licenses/LICENSE)
// 
