/* 
 * Header.cs
 * 
 *   Created: 2022-11-11-03:57:15
 *   Modified: 2022-11-11-03:57:15
 * 
 *   Author: Justin Chase <justin@justinwritescode.com>
 *   
 *   Copyright © 2022 Justin Chase, All Rights Reserved
 *      License: MIT (https://opensource.org/licenses/MIT)
 */
// BEGIN
//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/justinwritescode/Types/src/InterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
