# This workflow builds and deploys an mkdocs site to GitHub Pages
name: justinwritescode/docs cd

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs_cd:
    runs-on: ubuntu-latest
    environment: docs
    steps:
    - uses: justinwritescode/cd/docs-cd-deploy@latest
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        deploy_folder: "types"
